const DashboardMatches = [
  {
    id: 0,
    homeTeam: "Oklahoma City Thunder",
    homeImageURL: "https://example.com/oklahoma_city_thunder_logo.jpg",
    awayTeam: "Toronto Raptors",
    awayImageURL: "https://example.com/toronto_raptors_logo.jpg",
    prediction: "Toronto Raptors",
    winPercentage: 79,
    checked: false,
  },
  {
    id: 1,
    homeTeam: "Golden State Warriors",
    homeImageURL: "https://example.com/golden_state_warriors_logo.jpg",
    awayTeam: "Brooklyn Nets",
    awayImageURL: "https://example.com/brooklyn_nets_logo.jpg",
    prediction: "Brooklyn Nets",
    winPercentage: 62,
    checked: false,
  },
  {
    id: 2,
    homeTeam: "New York Knicks",
    homeImageURL: "https://example.com/new_york_knicks_logo.jpg",
    awayTeam: "Los Angeles Lakers",
    awayImageURL: "https://example.com/los_angeles_lakers_logo.jpg",
    prediction: "New York Knicks",
    winPercentage: 67,
    checked: false,
  },
  {
    id: 3,
    homeTeam: "Denver Nuggets",
    homeImageURL: "https://example.com/denver_nuggets_logo.jpg",
    awayTeam: "Houston Rockets",
    awayImageURL: "https://example.com/houston_rockets_logo.jpg",
    prediction: "Houston Rockets",
    winPercentage: 58,
    checked: false,
  },
  {
    id: 4,
    homeTeam: "Charlotte Hornets",
    homeImageURL: "https://example.com/charlotte_hornets_logo.jpg",
    awayTeam: "Philadelphia 76ers",
    awayImageURL: "https://example.com/philadelphia_76ers_logo.jpg",
    prediction: "Charlotte Hornets",
    winPercentage: 76,
    checked: false,
  },
  {
    id: 5,
    homeTeam: "Orlando Magic",
    homeImageURL: "https://example.com/orlando_magic_logo.jpg",
    awayTeam: "Cleveland Cavaliers",
    awayImageURL: "https://example.com/cleveland_cavaliers_logo.jpg",
    prediction: "Cleveland Cavaliers",
    winPercentage: 87,
    checked: false,
  },
  {
    id: 6,
    homeTeam: "Chicago Bulls",
    homeImageURL: "https://example.com/chicago_bulls_logo.jpg",
    awayTeam: "Miami Heat",
    awayImageURL: "https://example.com/miami_heat_logo.jpg",
    prediction: "Chicago Bulls",
    winPercentage: 64,
    checked: false,
  },
  {
    id: 7,
    homeTeam: "Memphis Grizzlies",
    homeImageURL: "https://example.com/memphis_grizzlies_logo.jpg",
    awayTeam: "Utah Jazz",
    awayImageURL: "https://example.com/utah_jazz_logo.jpg",
    prediction: "Memphis Grizzlies",
    winPercentage: 71,
    checked: false,
  },
  {
    id: 8,
    homeTeam: "Minnesota Timberwolves",
    homeImageURL: "https://example.com/minnesota_timberwolves_logo.jpg",
    awayTeam: "Indiana Pacers",
    awayImageURL: "https://example.com/indiana_pacers_logo.jpg",
    prediction: "Minnesota Timberwolves",
    winPercentage: 55,
    checked: false,
  },
  {
    id: 9,
    homeTeam: "Washington Wizards",
    homeImageURL: "https://example.com/washington_wizards_logo.jpg",
    awayTeam: "Dallas Mavericks",
    awayImageURL: "https://example.com/dallas_mavericks_logo.jpg",
    prediction: "Washington Wizards",
    winPercentage: 82,
    checked: false,
  },
  {
    id: 10,
    homeTeam: "San Antonio Spurs",
    homeImageURL: "https://example.com/san_antonio_spurs_logo.jpg",
    awayTeam: "Detroit Pistons",
    awayImageURL: "https://example.com/detroit_pistons_logo.jpg",
    prediction: "Detroit Pistons",
    winPercentage: 60,
    checked: false,
  },
  {
    id: 11,
    homeTeam: "Portland Trail Blazers",
    homeImageURL: "https://example.com/portland_trail_blazers_logo.jpg",
    awayTeam: "Sacramento Kings",
    awayImageURL: "https://example.com/sacramento_kings_logo.jpg",
    prediction: "Sacramento Kings",
    winPercentage: 74,
    checked: false,
  },
  {
    id: 12,
    homeTeam: "Milwaukee Bucks",
    homeImageURL: "https://example.com/milwaukee_bucks_logo.jpg",
    awayTeam: "Atlanta Hawks",
    awayImageURL: "https://example.com/atlanta_hawks_logo.jpg",
    prediction: "Atlanta Hawks",
    winPercentage: 81,
    checked: false,
  },
  {
    id: 13,
    homeTeam: "Boston Celtics",
    homeImageURL: "https://example.com/boston_celtics_logo.jpg",
    awayTeam: "LA Clippers",
    awayImageURL: "https://example.com/la_clippers_logo.jpg",
    prediction: "LA Clippers",
    winPercentage: 59,
    checked: false,
  },
  {
    id: 14,
    homeTeam: "Phoenix Suns",
    homeImageURL: "https://example.com/phoenix_suns_logo.jpg",
    awayTeam: "New Orleans Pelicans",
    awayImageURL: "https://example.com/new_orleans_pelicans_logo.jpg",
    prediction: "Phoenix Suns",
    winPercentage: 63,
    checked: false,
  },
  {
    id: 15,
    homeTeam: "LA Clippers",
    homeImageURL: "https://example.com/la_clippers_logo.jpg",
    awayTeam: "Chicago Bulls",
    awayImageURL: "https://example.com/chicago_bulls_logo.jpg",
    prediction: "LA Clippers",
    winPercentage: 88,
    checked: false,
  },
  {
    id: 16,
    homeTeam: "Houston Rockets",
    homeImageURL: "https://example.com/houston_rockets_logo.jpg",
    awayTeam: "Memphis Grizzlies",
    awayImageURL: "https://example.com/memphis_grizzlies_logo.jpg",
    prediction: "Memphis Grizzlies",
    winPercentage: 56,
    checked: false,
  },
  {
    id: 17,
    homeTeam: "Miami Heat",
    homeImageURL: "https://example.com/miami_heat_logo.jpg",
    awayTeam: "Phoenix Suns",
    awayImageURL: "https://example.com/phoenix_suns_logo.jpg",
    prediction: "Phoenix Suns",
    winPercentage: 70,
    checked: false,
  },
  {
    id: 18,
    homeTeam: "Cleveland Cavaliers",
    homeImageURL: "https://example.com/cleveland_cavaliers_logo.jpg",
    awayTeam: "Denver Nuggets",
    awayImageURL: "https://example.com/denver_nuggets_logo.jpg",
    prediction: "Cleveland Cavaliers",
    winPercentage: 65,
    checked: false,
  },
  {
    id: 19,
    homeTeam: "Dallas Mavericks",
    homeImageURL: "https://example.com/dallas_mavericks_logo.jpg",
    awayTeam: "Golden State Warriors",
    awayImageURL: "https://example.com/golden_state_warriors_logo.jpg",
    prediction: "Dallas Mavericks",
    winPercentage: 83,
    checked: false,
  },
  {
    id: 20,
    homeTeam: "Philadelphia 76ers",
    homeImageURL: "https://example.com/philadelphia_76ers_logo.jpg",
    awayTeam: "New York Knicks",
    awayImageURL: "https://example.com/new_york_knicks_logo.jpg",
    prediction: "New York Knicks",
    winPercentage: 68,
    checked: false,
  },
  {
    id: 21,
    homeTeam: "LA Lakers",
    homeImageURL: "https://example.com/los_angeles_lakers_logo.jpg",
    awayTeam: "San Antonio Spurs",
    awayImageURL: "https://example.com/san_antonio_spurs_logo.jpg",
    prediction: "LA Lakers",
    winPercentage: 72,
    checked: false,
  },
  {
    id: 22,
    homeTeam: "Indiana Pacers",
    homeImageURL: "https://example.com/indiana_pacers_logo.jpg",
    awayTeam: "Milwaukee Bucks",
    awayImageURL: "https://example.com/milwaukee_bucks_logo.jpg",
    prediction: "Indiana Pacers",
    winPercentage: 80,
    checked: false,
  },
  {
    id: 23,
    homeTeam: "Sacramento Kings",
    homeImageURL: "https://example.com/sacramento_kings_logo.jpg",
    awayTeam: "Washington Wizards",
    awayImageURL: "https://example.com/washington_wizards_logo.jpg",
    prediction: "Sacramento Kings",
    winPercentage: 74,
    checked: false,
  },
  {
    id: 24,
    homeTeam: "Atlanta Hawks",
    homeImageURL: "https://example.com/atlanta_hawks_logo.jpg",
    awayTeam: "Boston Celtics",
    awayImageURL: "https://example.com/boston_celtics_logo.jpg",
    prediction: "Boston Celtics",
    winPercentage: 55,
    checked: false,
  },
  {
    id: 25,
    homeTeam: "Utah Jazz",
    homeImageURL: "https://example.com/utah_jazz_logo.jpg",
    awayTeam: "Charlotte Hornets",
    awayImageURL: "https://example.com/charlotte_hornets_logo.jpg",
    prediction: "Utah Jazz",
    winPercentage: 66,
    checked: false,
  },
  {
    id: 26,
    homeTeam: "Toronto Raptors",
    homeImageURL: "https://example.com/toronto_raptors_logo.jpg",
    awayTeam: "Orlando Magic",
    awayImageURL: "https://example.com/orlando_magic_logo.jpg",
    prediction: "Toronto Raptors",
    winPercentage: 75,
    checked: false,
  },
  {
    id: 27,
    homeTeam: "Brooklyn Nets",
    homeImageURL: "https://example.com/brooklyn_nets_logo.jpg",
    awayTeam: "New Orleans Pelicans",
    awayImageURL: "https://example.com/new_orleans_pelicans_logo.jpg",
    prediction: "Brooklyn Nets",
    winPercentage: 61,
    checked: false,
  },
  {
    id: 28,
    homeTeam: "Detroit Pistons",
    homeImageURL: "https://example.com/detroit_pistons_logo.jpg",
    awayTeam: "Memphis Grizzlies",
    awayImageURL: "https://example.com/memphis_grizzlies_logo.jpg",
    prediction: "Detroit Pistons",
    winPercentage: 84,
    checked: false,
  },
  {
    id: 29,
    homeTeam: "Phoenix Suns",
    homeImageURL: "https://example.com/phoenix_suns_logo.jpg",
    awayTeam: "Indiana Pacers",
    awayImageURL: "https://example.com/indiana_pacers_logo.jpg",
    prediction: "Phoenix Suns",
    winPercentage: 69,
    checked: false,
  },
];

export default DashboardMatches