const DashboardMatches = [
  {
    id: 0,
    homeTeam: "Oklahoma City Thunder",
    awayTeam: "Toronto Raptors",
    prediction: "Toronto Raptors",
    winPercentage: 79,
    checked: false,
  },
  {
    id: 1,
    homeTeam: "Golden State Warriors",
    awayTeam: "Brooklyn Nets",
    prediction: "Brooklyn Nets",
    winPercentage: 62,
    checked: false,
  },
  {
    id: 2,
    homeTeam: "New York Knicks",
    awayTeam: "Los Angeles Lakers",
    prediction: "New York Knicks",
    winPercentage: 67,
    checked: false,
  },
  {
    id: 3,
    homeTeam: "Denver Nuggets",
    awayTeam: "Houston Rockets",
    prediction: "Houston Rockets",
    winPercentage: 58,
    checked: false,
  },
  {
    id: 4,
    homeTeam: "Charlotte Hornets",
    awayTeam: "Philadelphia 76ers",
    prediction: "Charlotte Hornets",
    winPercentage: 76,
    checked: false,
  },
  {
    id: 5,
    homeTeam: "Orlando Magic",
    awayTeam: "Cleveland Cavaliers",
    prediction: "Cleveland Cavaliers",
    winPercentage: 87,
    checked: false,
  },
  {
    id: 6,
    homeTeam: "Chicago Bulls",
    awayTeam: "Miami Heat",
    prediction: "Chicago Bulls",
    winPercentage: 64,
    checked: false,
  },
  {
    id: 7,
    homeTeam: "Memphis Grizzlies",
    awayTeam: "Utah Jazz",
    prediction: "Memphis Grizzlies",
    winPercentage: 71,
    checked: false,
  },
  {
    id: 8,
    homeTeam: "Minnesota Timberwolves",
    awayTeam: "Indiana Pacers",
    prediction: "Minnesota Timberwolves",
    winPercentage: 55,
    checked: false,
  },
  {
    id: 9,
    homeTeam: "Washington Wizards",
    awayTeam: "Dallas Mavericks",
    prediction: "Washington Wizards",
    winPercentage: 82,
    checked: false,
  },
  {
    id: 10,
    homeTeam: "San Antonio Spurs",
    awayTeam: "Detroit Pistons",
    prediction: "Detroit Pistons",
    winPercentage: 60,
    checked: false,
  },
  {
    id: 11,
    homeTeam: "Portland Trail Blazers",
    awayTeam: "Sacramento Kings",
    prediction: "Sacramento Kings",
    winPercentage: 74,
    checked: false,
  },
  {
    id: 12,
    homeTeam: "Milwaukee Bucks",
    awayTeam: "Atlanta Hawks",
    prediction: "Atlanta Hawks",
    winPercentage: 81,
    checked: false,
  },
  {
    id: 13,
    homeTeam: "Boston Celtics",
    awayTeam: "LA Clippers",
    prediction: "LA Clippers",
    winPercentage: 59,
    checked: false,
  },
  {
    id: 14,
    homeTeam: "Phoenix Suns",
    awayTeam: "New Orleans Pelicans",
    prediction: "Phoenix Suns",
    winPercentage: 63,
    checked: false,
  },
  {
    id: 15,
    homeTeam: "LA Clippers",
    awayTeam: "Chicago Bulls",
    prediction: "LA Clippers",
    winPercentage: 88,
    checked: false,
  },
  {
    id: 16,
    homeTeam: "Houston Rockets",
    awayTeam: "Memphis Grizzlies",
    prediction: "Memphis Grizzlies",
    winPercentage: 56,
    checked: false,
  },
  {
    id: 17,
    homeTeam: "Miami Heat",
    awayTeam: "Phoenix Suns",
    prediction: "Phoenix Suns",
    winPercentage: 70,
    checked: false,
  },
  {
    id: 18,
    homeTeam: "Cleveland Cavaliers",
    awayTeam: "Denver Nuggets",
    prediction: "Cleveland Cavaliers",
    winPercentage: 65,
    checked: false,
  },
  {
    id: 19,
    homeTeam: "Dallas Mavericks",
    awayTeam: "Golden State Warriors",
    prediction: "Dallas Mavericks",
    winPercentage: 83,
    checked: false,
  },
  {
    id: 20,
    homeTeam: "Philadelphia 76ers",
    awayTeam: "New York Knicks",
    prediction: "New York Knicks",
    winPercentage: 68,
    checked: false,
  },
  {
    id: 21,
    homeTeam: "LA Lakers",
    awayTeam: "San Antonio Spurs",
    prediction: "LA Lakers",
    winPercentage: 72,
    checked: false,
  },
  {
    id: 22,
    homeTeam: "Indiana Pacers",
    awayTeam: "Milwaukee Bucks",
    prediction: "Indiana Pacers",
    winPercentage: 80,
    checked: false,
  },
  {
    id: 23,
    homeTeam: "Sacramento Kings",
    awayTeam: "Washington Wizards",
    prediction: "Sacramento Kings",
    winPercentage: 74,
    checked: false,
  },
  {
    id: 24,
    homeTeam: "Atlanta Hawks",
    awayTeam: "Boston Celtics",
    prediction: "Boston Celtics",
    winPercentage: 55,
    checked: false,
  },
  {
    id: 25,
    homeTeam: "Utah Jazz",
    awayTeam: "Charlotte Hornets",
    prediction: "Utah Jazz",
    winPercentage: 66,
    checked: false,
  },
  {
    id: 26,
    homeTeam: "Toronto Raptors",
    awayTeam: "Orlando Magic",
    prediction: "Toronto Raptors",
    winPercentage: 75,
    checked: false,
  },
  {
    id: 27,
    homeTeam: "Brooklyn Nets",
    awayTeam: "New Orleans Pelicans",
    prediction: "Brooklyn Nets",
    winPercentage: 61,
    checked: false,
  },
  {
    id: 28,
    homeTeam: "Detroit Pistons",
    awayTeam: "Memphis Grizzlies",
    prediction: "Detroit Pistons",
    winPercentage: 84,
    checked: false,
  },
  {
    id: 29,
    homeTeam: "Phoenix Suns",
    awayTeam: "Indiana Pacers",
    prediction: "Phoenix Suns",
    winPercentage: 69,
    checked: false,
  },
];

export default DashboardMatches