const DashboardMatches = [
  {
    id: 0,
    home_team: "Oklahoma City Thunder",
    away_team: "Toronto Raptors",
    win: "Oklahoma City Thunder",
    prediction: "Oklahoma City Thunder",
    win_percentage: 79,
    checked: false,
  },
  {
    id: 1,
    home_team: "Golden State Warriors",
    away_team: "Brooklyn Nets",
    win: "Brooklyn Nets",
    prediction: "Brooklyn Nets",
    win_percentage: 62,
    checked: false,
  },
  {
    id: 2,
    home_team: "New York Knicks",
    away_team: "Los Angeles Lakers",
    win: "New York Knicks",
    prediction: "New York Knicks",
    win_percentage: 67,
    checked: false,
  },
  {
    id: 3,
    home_team: "Denver Nuggets",
    away_team: "Houston Rockets",
    win: "Houston Rockets",
    prediction: "Houston Rockets",
    win_percentage: 58,
    checked: false,
  },
  {
    id: 4,
    home_team: "Charlotte Hornets",
    away_team: "Philadelphia 76ers",
    win: "Charlotte Hornets",
    prediction: "Charlotte Hornets",
    win_percentage: 76,
    checked: false,
  },
  {
    id: 5,
    home_team: "Orlando Magic",
    away_team: "Cleveland Cavaliers",
    win: "Cleveland Cavaliers",
    prediction: "Cleveland Cavaliers",
    win_percentage: 87,
    checked: false,
  },
  {
    id: 6,
    home_team: "Chicago Bulls",
    away_team: "Miami Heat",
    win: "Chicago Bulls",
    prediction: "Chicago Bulls",
    win_percentage: 64,
    checked: false,
  },
  {
    id: 7,
    home_team: "Memphis Grizzlies",
    away_team: "Utah Jazz",
    win: "Memphis Grizzlies",
    prediction: "Memphis Grizzlies",
    win_percentage: 71,
    checked: false,
  },
  {
    id: 8,
    home_team: "Minnesota Timberwolves",
    away_team: "Indiana Pacers",
    win: "Minnesota Timberwolves",
    prediction: "Minnesota Timberwolves",
    win_percentage: 55,
    checked: false,
  },
  {
    id: 9,
    home_team: "Washington Wizards",
    away_team: "Dallas Mavericks",
    win: "Washington Wizards",
    prediction: "Washington Wizards",
    win_percentage: 82,
    checked: false,
  },
  {
    id: 10,
    home_team: "San Antonio Spurs",
    away_team: "Detroit Pistons",
    win: "Detroit Pistons",
    prediction: "Detroit Pistons",
    win_percentage: 60,
    checked: false,
  },
  {
    id: 11,
    home_team: "Portland Trail Blazers",
    away_team: "Sacramento Kings",
    win: "Sacramento Kings",
    prediction: "Sacramento Kings",
    win_percentage: 74,
    checked: false,
  },
  {
    id: 12,
    home_team: "Milwaukee Bucks",
    away_team: "Atlanta Hawks",
    win: "Atlanta Hawks",
    prediction: "Atlanta Hawks",
    win_percentage: 81,
    checked: false,
  },
  {
    id: 13,
    home_team: "Boston Celtics",
    away_team: "LA Clippers",
    win: "LA Clippers",
    prediction: "LA Clippers",
    win_percentage: 59,
    checked: false,
  },
  {
    id: 14,
    home_team: "Phoenix Suns",
    away_team: "New Orleans Pelicans",
    win: "Phoenix Suns",
    prediction: "Phoenix Suns",
    win_percentage: 63,
    checked: false,
  },
  {
    id: 15,
    home_team: "LA Clippers",
    away_team: "Chicago Bulls",
    win: "LA Clippers",
    prediction: "LA Clippers",
    win_percentage: 88,
    checked: false,
  },
  {
    id: 16,
    home_team: "Houston Rockets",
    away_team: "Memphis Grizzlies",
    win: "Memphis Grizzlies",
    prediction: "Memphis Grizzlies",
    win_percentage: 56,
    checked: false,
  },
  {
    id: 17,
    home_team: "Miami Heat",
    away_team: "Phoenix Suns",
    win: "Phoenix Suns",
    prediction: "Phoenix Suns",
    win_percentage: 70,
    checked: false,
  },
  {
    id: 18,
    home_team: "Cleveland Cavaliers",
    away_team: "Denver Nuggets",
    win: "Cleveland Cavaliers",
    prediction: "Cleveland Cavaliers",
    win_percentage: 65,
    checked: false,
  },
  {
    id: 19,
    home_team: "Dallas Mavericks",
    away_team: "Golden State Warriors",
    win: "Dallas Mavericks",
    prediction: "Dallas Mavericks",
    win_percentage: 83,
    checked: false,
  },
  {
    id: 20,
    home_team: "Philadelphia 76ers",
    away_team: "New York Knicks",
    win: "New York Knicks",
    prediction: "New York Knicks",
    win_percentage: 68,
    checked: false,
  },
  {
    id: 21,
    home_team: "LA Lakers",
    away_team: "San Antonio Spurs",
    win: "LA Lakers",
    prediction: "LA Lakers",
    win_percentage: 72,
    checked: false,
  },
  {
    id: 22,
    home_team: "Indiana Pacers",
    away_team: "Milwaukee Bucks",
    win: "Indiana Pacers",
    prediction: "Indiana Pacers",
    win_percentage: 80,
    checked: false,
  },
  {
    id: 23,
    home_team: "Sacramento Kings",
    away_team: "Washington Wizards",
    win: "Sacramento Kings",
    prediction: "Sacramento Kings",
    win_percentage: 74,
    checked: false,
  },
  {
    id: 24,
    home_team: "Atlanta Hawks",
    away_team: "Boston Celtics",
    win: "Boston Celtics",
    prediction: "Boston Celtics",
    win_percentage: 55,
    checked: false,
  },
  {
    id: 25,
    home_team: "Utah Jazz",
    away_team: "Charlotte Hornets",
    win: "Utah Jazz",
    prediction: "Utah Jazz",
    win_percentage: 66,
    checked: false,
  },
  {
    id: 26,
    home_team: "Toronto Raptors",
    away_team: "Orlando Magic",
    win: "Toronto Raptors",
    prediction: "Toronto Raptors",
    win_percentage: 75,
    checked: false,
  },
  {
    id: 27,
    home_team: "Brooklyn Nets",
    away_team: "New Orleans Pelicans",
    win: "Brooklyn Nets",
    prediction: "Brooklyn Nets",
    win_percentage: 61,
    checked: false,
  },
  {
    id: 28,
    home_team: "Detroit Pistons",
    away_team: "Memphis Grizzlies",
    win: "Detroit Pistons",
    prediction: "Detroit Pistons",
    win_percentage: 84,
    checked: false,
  },
  {
    id: 29,
    home_team: "Phoenix Suns",
    away_team: "Indiana Pacers",
    win: "Phoenix Suns",
    prediction: "Phoenix Suns",
    win_percentage: 69,
    checked: false,
  },
];

export default DashboardMatches;
