export const FETCH_PREDICTIONS_DATA_SUCCESS = 'FETCH_PREDICTIONS_DATA_SUCCESS';
export const FETCH_PREDICTIONS_DATA_FAILURE = 'FETCH_PREDICTIONS_DATA_FAILURE';

export const FETCH_HISTORY_DATA_SUCCESS = 'FETCH_HISTORY_DATA_SUCCESS';
export const FETCH_HISTORY_DATA_FAILURE = 'FETCH_HISTORY_DATA_FAILURE';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAILURE = 'SET_USER_FAILURE';
