export const FETCH_PREDICTIONS_DATA_SUCCESS = 'FETCH_PREDICTIONS_DATA_SUCCESS';
export const FETCH_PREDICTIONS_DATA_FAILURE = 'FETCH_PREDICTIONS_DATA_FAILURE';

export const FETCH_HISTORY_DATA_SUCCESS = 'FETCH_HISTORY_DATA_SUCCESS';
export const FETCH_HISTORY_DATA_FAILURE = 'FETCH_HISTORY_DATA_FAILURE';
